openapi: 3.0.0
info:
  title: Task API
  description: This is a simple task API
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/fayaz-abdul/task-api/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: task
  description: Task resource
paths:
  /task:
    get:
      tags:
      - task
      summary: get task list
      description: Get all the tasks in system
      operationId: getAllTasks
      responses:
        "200":
          description: list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        "400":
          description: bad input parameter
    post:
      tags:
      - task
      summary: adds a task resource
      description: Adds a task to the system
      operationId: addTask
      requestBody:
        description: Task to add
        content:
          application/json:
            schema:
              type: string
              format: byte
      responses:
        "201":
          description: task created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        "400":
          description: invalid input, object invalid
        "409":
          description: an existing item already exists
  /task/{id}:
    get:
      tags:
      - task
      summary: Get task by id
      operationId: getTaskById
      parameters:
      - name: id
        in: path
        description: The id of task to be fetched.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        "400":
          description: Invalid task id provided
        "404":
          description: Task not found
    put:
      tags:
      - task
      summary: Updated task
      description: Update the task resource.
      operationId: updateTask
      parameters:
      - name: id
        in: path
        description: id to be updated
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Updated user object
        content:
          application/json:
            schema:
              type: string
              format: byte
        required: true
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        "400":
          description: Invalid data provided
        "404":
          description: id not found
components:
  schemas:
    Task:
      required:
      - createdDate
      - description
      - id
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        description:
          type: string
          example: Descripton for the task
        createdTime:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z